name: Deploy WAR to Azure Web App

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Specify the Java version you need

    - name: Build WAR file
      run: |
        ./mvnw clean package  # Adjust this command based on your build tool

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: '<YOUR_AZURE_WEB_APP_NAME>'  # Replace with your Azure Web App name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Set this secret in your GitHub repository
        package: '*.war'  # Adjust the path to your WAR file if necessary
